<h1><center> PPOLS564: Foundations of Data Science </center><h1>
<h3><center> Lecture 13 <br><br><font color='grey'> Matrix Operations </font></center></h3>

# Concepts For today:

- (Cont.) Matrix Multiplication 
- Matrix Addition & Subtraction 
- Transposing Matrices
- Different Types of Matrices
- Using Numpy

## Note
In the following lectures, we'll delve into exploring linear algebra. Note that I'll be using some code to help generate some interactive visualizes for some concepts. To use this code yourself, two things must be true: (1) the `bokeh` module must be installed, and (2) the `visualize.py` script must be in the same file director as this notebook and the jupyter notebook must be activated from that location.

Finally, note that these lecture slides are intended to be supplementary to the lectures and readings.

In [201]:
import numpy as np
from visualize import LinearAlgebra as vla
plot = vla()

## Multiplying Matrices

What happens when we want to perform two transformation simultaneously?

$$ g \circ f: x \mapsto s \mapsto y $$

$$ g(\vec{x}) = \vec{s}$$

$$ f(\vec{s}) = y $$

We can represent this as the multiplication of two (or more) matrices.

$$ f(g(\vec{x})) = \textbf{A}_{2x2}\textbf{B}_{2x2}  \vec{x}$$

That is, we transform $\vec{x}$ by $\textbf{B}$ and then transform that resulting vector by $\textbf{A}$ much as we would with the nested function $f(g(\vec{x}))$. 

In [202]:
A = np.array([[ 1., -1.],[ 0.,  3.]])
A

array([[ 1., -1.],
       [ 0.,  3.]])

In [203]:
B = np.array([[-3. ,  1. ],[ 0.5,  2.3]])
B

array([[-3. ,  1. ],
       [ 0.5,  2.3]])

In [204]:
a = np.array([1,2])
a

array([1, 2])

In [205]:
a_new = B.dot(a)
a_new

array([-1. ,  5.1])

In [206]:
A.dot(a_new)

array([-6.1, 15.3])

This is equivalent to...

In [207]:
A.dot(B).dot(a)

array([-6.1, 15.3])

#### Now visually

In [209]:
plot.graph(25,grid=True)
plot.vector(a)
plot.show()

In [210]:
plot.clear()
plot.change_basis(B)
plot.graph(25,grid=True)
plot.vector(a)
plot.show()

In [211]:
plot.clear()
plot.change_basis(A.dot(B))
plot.graph(25,grid=True)
plot.vector(a)
plot.show()

In [212]:
# Let's do this all on in one go.
plot.clear().graph(25)
plot.vector(a)
plot.vector(A.dot(B).dot(a),add_color="purple")
plot.show()

### Multiplying two matrices by hand 

$$\textbf{A}_{mxn} = 
                     \begin{bmatrix}
                         \vec{a}_{1} & \vec{a}_{2} & \dots & \vec{a}_{n}\\
                     \end{bmatrix} = 
                    \begin{bmatrix} a_{11} & a_{12} & \dots & a_{1n}  \\ 
                                     a_{21}  & a_{22} & \dots & a_{2n} \\
                                     \vdots & \vdots & \ddots & \vdots \\
                                     a_{m1}  & a_{m2} & \dots & a_{mn} \\
                     \end{bmatrix} $$
                     
$$\textbf{B}_{nxk} = 
                    \begin{bmatrix}
                         \vec{b}_{1} & \vec{b}_{2} & \dots & \vec{b}_{k}\\
                     \end{bmatrix}  = 
                    \begin{bmatrix} b_{11} & b_{12} & \dots & b_{1k}  \\ 
                                     b_{21}  & b_{22} & \dots & b_{2k} \\
                                     \vdots & \vdots & \ddots & \vdots \\
                                     b_{n1}  & b_{n2} & \dots & b_{nk} \\
                     \end{bmatrix}$$
                     
Note that to multiply two matrices, their corresponding dimensions must align. Why? 

$$m \times \textbf{n}~~\textbf{n}\times k $$

Think of the $\textbf{A}$ as performing a linear transformation on each column vector of $\textbf{B}$

$$ \textbf{A}_{m \times \textbf{n}} \textbf{B}_{\textbf{n}\times k} = 
                     \begin{bmatrix}
                         \textbf{A} \vec{b}_{1} & \textbf{A} \vec{b}_{2} & \dots & \textbf{A} \vec{b}_{k}\\
                     \end{bmatrix}$$
                     
                     
$$
\begin{bmatrix}
 [a_{11} b_{11} + \dots + a_{1n} b_{n1} ] & [a_{11} b_{12} + \dots + a_{1n} b_{n2} ] & \dots & [a_{11} b_{1k} + \dots + a_{1n} b_{nk} ]\\
 \vdots & \vdots & \vdots & \vdots \\
 [a_{m1} b_{11} + \dots + a_{mn} b_{n1} ] & [a_{m1} b_{22} + \dots + a_{mn} b_{n2} ] & \dots & [a_{m1} b_{1k} + \dots + a_{mn} b_{nk} ]
\end{bmatrix}$$

$$ \textbf{A}_{m \times \textbf{n}} \textbf{B}_{\textbf{n}\times k} = \textbf{C}_{m\times k} $$

**Example**:

$$\textbf{A}_{2x3} = 
                    \begin{bmatrix} 1 & 3 & 1  \\ 
                                    0 & 1 & -1 \\
                     \end{bmatrix} $$

$$\textbf{B}_{3x2} = 
                    \begin{bmatrix} 2 & 1 \\ 
                                    -1 & -2 \\
                                    4 & 3 \\
                     \end{bmatrix} $$
                     
                     
$$ \textbf{A}_{2x3} \textbf{B}_{3x2} $$

$$ \begin{bmatrix}
   \textbf{A}\begin{bmatrix} 2  \\ -1 \\ 4 \\ \end{bmatrix} &
   \textbf{A}\begin{bmatrix} 1 \\ -2 \\ 3 \\ \end{bmatrix} 
   \end{bmatrix} $$
   
   
$$ \begin{bmatrix}
   \begin{bmatrix} 1  \\ 3 \\ 1 \\ \end{bmatrix} \begin{bmatrix} 2  \\ -1 \\ 4 \\ \end{bmatrix} &
   \begin{bmatrix} 1  \\ 3 \\ 1 \\ \end{bmatrix}\begin{bmatrix} 1 \\ -2 \\ 3 \\ \end{bmatrix} \\
   \begin{bmatrix} 0  \\ 1 \\ -1 \\ \end{bmatrix} \begin{bmatrix} 2  \\ -1 \\ 4 \\ \end{bmatrix} &
   \begin{bmatrix} 0  \\ 1 \\ -1 \\ \end{bmatrix}  \begin{bmatrix} 1 \\ -2 \\ 3 \\ \end{bmatrix} 
   \end{bmatrix} $$
   
$$ \begin{bmatrix}
    1(2) + 3(-1) + 1(4) & 1(1) + 3(-2) + 1(3)\\
    0(2) + 1(-1) + -1(4) & 0(1) + 1(-2) + -1(3)
   \end{bmatrix} $$
   
$$ \begin{bmatrix}
    3 & -2\\
    -5 & -5
   \end{bmatrix} $$

In [32]:
A = np.array([[1,3,1],[0,1,-1]])
B = np.array([[2,1],[-1,-2],[4,3]])
print(A)
print(B)

[[ 1  3  1]
 [ 0  1 -1]]
[[ 2  1]
 [-1 -2]
 [ 4  3]]


In [33]:
A.dot(B)

array([[ 3, -2],
       [-5, -5]])

## Properties of Matrix Multiplication 

<font color = "grey">~~**COMMUNITIVE**~~</font>

<font color = "grey">$$ \textbf{A} \textbf{B} \ne \textbf{B} \textbf{A}  $$  </font>


**ASSOCIATIVE**

$$(\textbf{A} \textbf{B}) \textbf{C} = \textbf{A} (\textbf{B} \textbf{C}) = \textbf{A} \textbf{B} \textbf{C} $$


**DISTRIBUTIVE**

$$\textbf{A}(\textbf{B} + \textbf{C}) = \textbf{A}\textbf{B} + \textbf{A}\textbf{C}$$

But remember it's not communicative, so order matters!

-----

# Matrix Addition and Substitution

Much like vectors, multiply and adding vectors is done so element-wise.

$$\textbf{B}_{3x2} = 
                    \begin{bmatrix} 2 & 1 \\ 
                                    -1 & -2 \\
                                    4 & 3 \\
                     \end{bmatrix} $$

$$\textbf{C}_{3x2} = 
                    \begin{bmatrix} 1 & 2 \\ 
                                    -2 & 1 \\
                                    2 & 1 \\
                     \end{bmatrix} $$

In [4]:
B = np.array([[2,1],[-1,-2],[4,3]])
B

array([[ 2,  1],
       [-1, -2],
       [ 4,  3]])

In [6]:
C = np.array([[1,2],[-2,1],[2,1]])
C

array([[ 1,  2],
       [-2,  1],
       [ 2,  1]])

### Addition 
$$ \textbf{B}_{3x2} + \textbf{C}_{3x2} $$


$$   \begin{bmatrix} 2 & 1 \\ 
                                    -1 & -2 \\
                                    4 & 3 \\
                     \end{bmatrix} +  \begin{bmatrix} 1 & 2 \\ 
                                    -2 & 1 \\
                                    2 & 1 \\
                     \end{bmatrix} $$
                     
                     
$$  \begin{bmatrix} 2 + 1 & 1 + 2 \\ 
                                   -1 + -2 & -2 + 1 \\
                                    4 + 2& 3 + 1\\
                     \end{bmatrix} $$  
                     
                     
$$  \begin{bmatrix} 3 & 3 \\ 
                   -3 & -1 \\
                    6 & 4\\
    \end{bmatrix} $$                       

In [8]:
B + C

array([[ 3,  3],
       [-3, -1],
       [ 6,  4]])

### Subtraction 
$$ \textbf{B}_{3x2} + \textbf{C}_{3x2} $$


$$   \begin{bmatrix} 2 & 1 \\ 
                                    -1 & -2 \\
                                    4 & 3 \\
                     \end{bmatrix} +  \begin{bmatrix} 1 & 2 \\ 
                                    -2 & 1 \\
                                    2 & 1 \\
                     \end{bmatrix} $$
                     
                     
$$  \begin{bmatrix} 2 - 1 & 1 - 2 \\ 
                                   -1 - -2 & -2 - 1 \\
                                    4 - 2& 3 - 1\\
                     \end{bmatrix} $$  
                     
                     
$$  \begin{bmatrix} 1 & -1 \\ 
                    1 & -3 \\
                    2 & 2\\
    \end{bmatrix} $$                       

In [10]:
B - C

array([[ 1, -1],
       [ 1, -3],
       [ 2,  2]])

#### Must have corresponding elements

In [13]:
D = np.array([[1,2],[2,4]])
D

array([[1, 2],
       [2, 4]])

In [14]:
B - D

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

# Transposing a Matrix


$$\textbf{A}_{2x3} = \begin{bmatrix} a_{11} & a_{12} & a_{13}  \\ 
                                     a_{21}  & a_{22} & a_{23} \\
                     \end{bmatrix} $$
                     
                     

$$\textbf{A}^T_{3x2} = \begin{bmatrix} a_{11} & a_{12} \\ 
                                       a_{21}  & a_{22}\\
                                       a_{31}  & a_{32}\\
                     \end{bmatrix} $$

In [227]:
A = np.array([[1,2,3],
             [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [228]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Properties

$$ (\textbf{A}^T)^T = A $$

$$ (\textbf{A} + \textbf{B})^T = \textbf{A}^T + \textbf{B}^T $$

$$ (C\textbf{A})^T = cA^T $$

$$ (\textbf{A}\textbf{B})^T = \textbf{A}^T \textbf{B}^T $$

## "Squaring" a matrix

Recall that to multiply two matrices, their rows and columns must correspond. We can manufacture this condition by taking the dot product of a matrix transposed with itself.

In [229]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [230]:
At = A.T
At

array([[1, 4],
       [2, 5],
       [3, 6]])

In [231]:
A.dot(At)

array([[14, 32],
       [32, 77]])

In [232]:
At.dot(A)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

What is going on here?

$$ \textbf{A}_{2x3} \textbf{A}^T_{3x2} $$

$$\begin{bmatrix} a_{11} & a_{12} & a_{13}  \\ 
                                     a_{21}  & a_{22} & a_{23} \\
                     \end{bmatrix} 
                     \begin{bmatrix} a_{11} & a_{12} \\ 
                                       a_{21}  & a_{22}\\
                                       a_{31}  & a_{32}\\
                     \end{bmatrix} $$
                     
$$  \begin{bmatrix} a_{11}a_{11} + a_{12}a_{21}  + a_{13}a_{31} &  a_{11}a_{11}  + a_{12}a_{21} + a_{13}a_{31}\\ 
                    a_{21}a_{11}  + a_{22}a_{21} + a_{23}a_{31} &  a_{21}a_{12}  + a_{22}a_{22} + a_{23}a_{32}\\
    \end{bmatrix}  $$  
    
With numbers this time ...    
$$\begin{bmatrix} 1 & 2 & 3  \\ 
                   4  & 5 & 6 \\
                     \end{bmatrix} 
                     \begin{bmatrix} 1 & 4\\ 
                                       2  & 5\\
                                       3  & 6\\
                     \end{bmatrix} $$
                     
$$  \begin{bmatrix} 1(1) + (2)(2) + (3)(3) &  1(4) + 2(5) + 3(6)\\ 
                    4(1) + 5(2) + 3(6) &  4(4) + (5)(5) + (6)(6)\\
    \end{bmatrix}  $$     
    
$$  \begin{bmatrix}14 &  32\\ 
                    32&  77\\
    \end{bmatrix}  $$     
    
Given what we know about vector dot products...

$$  \begin{bmatrix}
    length &  projection\\ 
    projection &  length\\
    \end{bmatrix}  $$  

# Different Types of Matrices

In [126]:
X = np.random.randn(25).reshape(5,5).round(2)
X

array([[-0.19,  2.5 , -1.31,  0.33,  1.45],
       [ 0.23, -0.57, -0.67, -1.05, -2.1 ],
       [ 1.34,  1.56,  0.66,  0.15,  0.56],
       [ 0.12,  0.6 ,  1.15,  0.89, -1.81],
       [ 0.62,  0.8 , -0.21,  0.14, -0.42]])

### Symmetric Matrices

In [82]:
X.dot(X.T)

array([[ 3.0438,  1.1467,  2.607 , -2.8544,  1.1582],
       [ 1.1467,  4.8034, -1.5405, -2.0086,  0.5347],
       [ 2.607 , -1.5405,  7.1235,  0.9024,  0.9135],
       [-2.8544, -2.0086,  0.9024,  7.1479,  0.1269],
       [ 1.1582,  0.5347,  0.9135,  0.1269,  1.8747]])

### Upper Triangle Matrices

In [75]:
np.triu(X)

array([[ 0.14, -0.29,  1.38, -0.39, -0.94],
       [ 0.  ,  0.55, -0.24, -1.88, -0.95],
       [ 0.  ,  0.  ,  1.29,  0.09, -0.24],
       [ 0.  ,  0.  ,  0.  , -0.27,  2.21],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.51]])

### Lower Triangle Matrices

In [76]:
# Lower Triangle
np.tril(X)

array([[ 0.14,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.08,  0.55,  0.  ,  0.  ,  0.  ],
       [-0.24, -2.31,  1.29,  0.  ,  0.  ],
       [-0.82, -0.97, -0.76, -0.27,  0.  ],
       [ 0.55,  0.  ,  0.95, -0.64,  0.51]])

### Diagonal Matrices

In [78]:
np.diag(np.array([4,2,10,-1]))

array([[ 4,  0,  0,  0],
       [ 0,  2,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, -1]])

### Zero Matrices

In [84]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Idempotent Matrices

In [89]:
P = np.array([[2,-2,-4],[-1,3,4],[1,-2,-3]])
P

array([[ 2, -2, -4],
       [-1,  3,  4],
       [ 1, -2, -3]])

In [90]:
P.dot(P)

array([[ 2, -2, -4],
       [-1,  3,  4],
       [ 1, -2, -3]])

### Identity Matrix

In [248]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Note that an identity matrix is also a diagonal and idempotent matrix.

In [250]:
I.dot(I)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [251]:
I.dot(X)

array([[-0.19,  2.5 , -1.31,  0.33,  1.45],
       [ 0.23, -0.57, -0.67, -1.05, -2.1 ],
       [ 1.34,  1.56,  0.66,  0.15,  0.56],
       [ 0.12,  0.6 ,  1.15,  0.89, -1.81],
       [ 0.62,  0.8 , -0.21,  0.14, -0.42]])

### Sparse Matrices

In [94]:
X = np.zeros((10,10))
X[[1,4,6,5,2],[1,5,3,5,1]] = 1
X

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [104]:
np.nonzero(X)

(array([1, 2, 4, 5, 6]), array([1, 1, 5, 5, 3]))

In [98]:
from scipy import sparse
print(sparse.csc_matrix(X))

  (1, 1)	1.0
  (2, 1)	1.0
  (6, 3)	1.0
  (4, 5)	1.0
  (5, 5)	1.0


----
# Basics of Using Numpy

### Vectors, Matrices, and ndimensional Arrays

In [34]:
# vector as a list
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [35]:
# A matrix is a nested list
M = np.array([[1,2,3,4],
             [2,3,4,1],
             [-1,1,2,1]])
print(M)
M.shape

[[ 1  2  3  4]
 [ 2  3  4  1]
 [-1  1  2  1]]


(3, 4)

In [36]:
#  An ndimensional array is a nested list
A = np.array([
              [
                [1,2,3,4],
                [2,3,4,1],
                [-1,1,2,1]
              ],
             [
                 [1,2,3,4],
                 [2,3,4,1],
                 [-1,1,2,1]]
              ])
print(A)
A.shape

[[[ 1  2  3  4]
  [ 2  3  4  1]
  [-1  1  2  1]]

 [[ 1  2  3  4]
  [ 2  3  4  1]
  [-1  1  2  1]]]


(2, 3, 4)

### Generating Arrays

In [37]:
np.arange(1, # start
          5, # stop
          .5 # by
         )

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [38]:
# evenly spaced values for between the interval for the number requested
np.linspace(1,5,10) 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [39]:
# Generate 10 random numbers
np.random.randn(10) 

array([-2.36136353,  0.25935499,  0.19370782,  0.13043243,  1.50064783,
        0.38198906, -0.43939266, -0.27897491, -0.60783785,  0.80932312])

In [40]:
# Also, we can generate random values from known distributions
np.random.binomial(1,.5,10) # coin flip distribution

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 0])

In [41]:
np.random.normal(5,1,10) # normal (continuous) distribution

array([3.11669063, 6.03848886, 3.76576751, 3.32417661, 4.64763258,
       5.67540932, 4.04703247, 4.91516121, 4.16808634, 4.7597851 ])

In [42]:
np.random.poisson(1,10) # count distribution

array([0, 0, 1, 3, 1, 2, 0, 0, 0, 0])

In [43]:
np.random.uniform(1,5,10) # uniform distribution

array([1.58986647, 1.2823207 , 4.29460437, 4.54977674, 2.78640906,
       3.69769616, 1.22144169, 2.47988784, 4.97414065, 4.31116983])

### Reshaping Arrays

In [44]:
M.shape

(3, 4)

In [45]:
M.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 2,  3],
       [ 4,  1],
       [-1,  1],
       [ 2,  1]])

In [46]:
M.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  2,  3],
       [ 4,  1, -1],
       [ 1,  2,  1]])

In [47]:
# Can only reshape given the appropriate dimensions
# M.reshape(10,2)

In [48]:
# use negative 1 to guess the dimension
P = np.random.randn(50).reshape(5,-1)
P.shape

(5, 10)

In [49]:
# Alternative way to change the shape
P.shape = 10,5
P.shape

(10, 5)

## Generating Matrices

In [50]:
# Matrix full of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
# Matrix full of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
# Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
# empty container
empty_array = np.empty((2,3))
empty_array

array([[4.9e-324, 1.5e-323, 4.9e-324],
       [0.0e+000, 4.9e-324,      nan]])

Generating a matrix similar to the one you already have

In [54]:
np.ones_like(P)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
np.zeros_like(P)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Indexing and Slicing

```
M[row,column]
```

In [56]:
X = np.linspace(1,25,25).reshape(5,5)
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [57]:
X[0] # index first row 

array([1., 2., 3., 4., 5.])

In [58]:
X[:,0] # index first column

array([ 1.,  6., 11., 16., 21.])

In [59]:
X[0,0] # index a specific cell 

1.0

In [60]:
# Can use : or ... for a complete subsection
print(X[:,1])
print(X[...,1])

[ 2.  7. 12. 17. 22.]
[ 2.  7. 12. 17. 22.]


In [61]:
# slice rows and columns
X[0:3,0:3] 

array([[ 1.,  2.,  3.],
       [ 6.,  7.,  8.],
       [11., 12., 13.]])

In [62]:
# slice rows and columns
X[:3,:3] 

array([[ 1.,  2.,  3.],
       [ 6.,  7.,  8.],
       [11., 12., 13.]])

In [63]:
X[-1,:] # last row

array([21., 22., 23., 24., 25.])

In [64]:
X[:,-1] # last column

array([ 5., 10., 15., 20., 25.])

Demand specific indices (similar to `R`'s functionality)

In [65]:
X[[3,0,2],:]

array([[16., 17., 18., 19., 20.],
       [ 1.,  2.,  3.,  4.,  5.],
       [11., 12., 13., 14., 15.]])

In [66]:
X[:,[3,0,2]]

array([[ 4.,  1.,  3.],
       [ 9.,  6.,  8.],
       [14., 11., 13.],
       [19., 16., 18.],
       [24., 21., 23.]])

### Reassignment

In [67]:
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [68]:
X[:3,:3] = 0
X

array([[ 0.,  0.,  0.,  4.,  5.],
       [ 0.,  0.,  0.,  9., 10.],
       [ 0.,  0.,  0., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [69]:
X[1,2] = -999
X[4,4] = -999

In [70]:
X

array([[   0.,    0.,    0.,    4.,    5.],
       [   0.,    0., -999.,    9.,   10.],
       [   0.,    0.,    0.,   14.,   15.],
       [  16.,   17.,   18.,   19.,   20.],
       [  21.,   22.,   23.,   24., -999.]])

### Printing Numpy Arrays

np automatically truncates the data when printing. Handy when you have _alot_ of data

In [71]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [72]:
# We can adjust these settings
np.set_printoptions(threshold=None)
print(np.arange(100).reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### Handling Multiple Data Types

In [73]:
T = np.array([['a','b','c'],[1,2,3],[.3,.55,1.2]])
T

array([['a', 'b', 'c'],
       ['1', '2', '3'],
       ['0.3', '0.55', '1.2']], dtype='<U4')

In [74]:
T = np.array([[1,2,3],[.3,.55,1.2]])
T

array([[1.  , 2.  , 3.  ],
       [0.3 , 0.55, 1.2 ]])

We'll rely on Pandas Data Frames when using use multiple data types.

### Some Useful Methods

In [75]:
X = np.random.randn(25).reshape(5,5)
X = X.round(2)
X

array([[ 1.19,  0.25,  2.08, -1.36,  0.49],
       [-1.99, -0.88,  0.98, -1.21,  0.14],
       [-0.62,  1.19,  0.97, -0.65,  0.09],
       [-0.59,  1.95, -0.99, -0.98, -0.8 ],
       [ 1.  ,  0.3 , -2.21, -1.03, -1.25]])

In [76]:
# Diagonal of a matrix
np.diag(X)

array([ 1.19, -0.88,  0.97, -0.98, -1.25])

In [79]:
# Index Location of the maximum value
np.argmax(X)

2

In [80]:
# Index Location of the minmum value
np.argmin(X)

22

In [81]:
print(X.flatten()[np.argmax(X)])
print(X.flatten()[np.argmin(X)])

2.08
-2.21


In [82]:
# Scan where a condition holds
np.where(X > 0)

(array([0, 0, 0, 0, 1, 1, 2, 2, 2, 3, 4, 4]),
 array([0, 1, 2, 4, 2, 4, 1, 2, 4, 1, 0, 1]))

In [83]:
X[np.where(X > 0)]

array([1.19, 0.25, 2.08, 0.49, 0.98, 0.14, 1.19, 0.97, 0.09, 1.95, 1.  ,
       0.3 ])

In [84]:
X[np.where(X < 0)]

array([-1.36, -1.99, -0.88, -1.21, -0.62, -0.65, -0.59, -0.99, -0.98,
       -0.8 , -2.21, -1.03, -1.25])

In [85]:
# Count the number of non-zero entries
np.count_nonzero(np.array([1,0,8,0,1]))

3

In [86]:
# scan for missing values
X[1,2] = np.nan
X[3,3] = np.nan
X[4,1] = np.nan
np.isnan(X)

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False,  True, False, False, False]])

In [87]:
~np.isnan(X) # are not NAs

array([[ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True, False,  True,  True,  True]])

In [88]:
# Replace missing values with zero
X[np.where(np.isnan(X))] = 0
X

array([[ 1.19,  0.25,  2.08, -1.36,  0.49],
       [-1.99, -0.88,  0.  , -1.21,  0.14],
       [-0.62,  1.19,  0.97, -0.65,  0.09],
       [-0.59,  1.95, -0.99,  0.  , -0.8 ],
       [ 1.  ,  0.  , -2.21, -1.03, -1.25]])

This is only scratching the surface! Play around with the library yourself!