<h1><center> PPOLS564: Foundations of Data Science </center><h1>
<h3><center> Lecture 13 <br><br><font color='grey'> Supplement: Basics of Using Numpy </font></center></h3>

In [1]:
import numpy as np

# Basics of Using Numpy

### Vectors, Matrices, and ndimensional Arrays

In [2]:
# vector as a list
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [3]:
# A matrix is a nested list
M = np.array([[1,2,3,4],
             [2,3,4,1],
             [-1,1,2,1]])
print(M)
M.shape

[[ 1  2  3  4]
 [ 2  3  4  1]
 [-1  1  2  1]]


(3, 4)

In [4]:
#  An ndimensional array is a nested list
A = np.array([
              [
                [1,2,3,4],
                [2,3,4,1],
                [-1,1,2,1]
              ],
             [
                 [1,2,3,4],
                 [2,3,4,1],
                 [-1,1,2,1]]
              ])
print(A)
A.shape

[[[ 1  2  3  4]
  [ 2  3  4  1]
  [-1  1  2  1]]

 [[ 1  2  3  4]
  [ 2  3  4  1]
  [-1  1  2  1]]]


(2, 3, 4)

### Generating Arrays

In [5]:
np.arange(1, # start
          5, # stop
          .5 # by
         )

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:
# evenly spaced values for between the interval for the number requested
np.linspace(1,5,10) 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [7]:
# Generate 10 random numbers
np.random.randn(10) 

array([ 0.48889019,  1.12339341,  1.61448404, -0.39869267,  0.98992508,
       -0.19418219, -0.74157549,  0.18190261,  1.56174387, -1.42085644])

In [8]:
# Also, we can generate random values from known distributions
np.random.binomial(1,.5,10) # coin flip distribution

array([1, 0, 1, 0, 0, 0, 1, 0, 1, 1])

In [9]:
np.random.normal(5,1,10) # normal (continuous) distribution

array([5.53198748, 6.29651782, 5.7383529 , 6.70058287, 5.65144088,
       5.34565048, 3.56580303, 7.08599667, 5.51646035, 4.32563675])

In [10]:
np.random.poisson(1,10) # count distribution

array([0, 1, 1, 0, 1, 0, 1, 0, 0, 4])

In [11]:
np.random.uniform(1,5,10) # uniform distribution

array([1.45672954, 1.19987823, 3.45937598, 3.54149286, 1.78364077,
       3.60736663, 1.37101028, 1.06580815, 3.17553457, 3.98688487])

### Reshaping Arrays

In [12]:
M.shape

(3, 4)

In [13]:
M.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 2,  3],
       [ 4,  1],
       [-1,  1],
       [ 2,  1]])

In [14]:
M.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  2,  3],
       [ 4,  1, -1],
       [ 1,  2,  1]])

In [15]:
# Can only reshape given the appropriate dimensions
# M.reshape(10,2)

In [16]:
# use negative 1 to guess the dimension
P = np.random.randn(50).reshape(5,-1)
P.shape

(5, 10)

In [17]:
# Alternative way to change the shape
P.shape = 10,5
P.shape

(10, 5)

## Generating Matrices

In [18]:
# Matrix full of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# Matrix full of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# empty container
empty_array = np.empty((2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

Generating a matrix similar to the one you already have

In [22]:
np.ones_like(P)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.zeros_like(P)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Indexing and Slicing

```
M[row,column]
```

In [24]:
X = np.linspace(1,25,25).reshape(5,5)
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [25]:
X[0] # index first row 

array([1., 2., 3., 4., 5.])

In [26]:
X[:,0] # index first column

array([ 1.,  6., 11., 16., 21.])

In [27]:
X[0,0] # index a specific cell 

1.0

In [28]:
# Can use : or ... for a complete subsection
print(X[:,1])
print(X[...,1])

[ 2.  7. 12. 17. 22.]
[ 2.  7. 12. 17. 22.]


In [29]:
# slice rows and columns
X[0:3,0:3] 

array([[ 1.,  2.,  3.],
       [ 6.,  7.,  8.],
       [11., 12., 13.]])

In [30]:
# slice rows and columns
X[:3,:3] 

array([[ 1.,  2.,  3.],
       [ 6.,  7.,  8.],
       [11., 12., 13.]])

In [31]:
X[-1,:] # last row

array([21., 22., 23., 24., 25.])

In [32]:
X[:,-1] # last column

array([ 5., 10., 15., 20., 25.])

Demand specific indices (similar to `R`'s functionality)

In [33]:
X[[3,0,2],:]

array([[16., 17., 18., 19., 20.],
       [ 1.,  2.,  3.,  4.,  5.],
       [11., 12., 13., 14., 15.]])

In [34]:
X[:,[3,0,2]]

array([[ 4.,  1.,  3.],
       [ 9.,  6.,  8.],
       [14., 11., 13.],
       [19., 16., 18.],
       [24., 21., 23.]])

### Reassignment

In [35]:
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [36]:
X[:3,:3] = 0
X

array([[ 0.,  0.,  0.,  4.,  5.],
       [ 0.,  0.,  0.,  9., 10.],
       [ 0.,  0.,  0., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [37]:
X[1,2] = -999
X[4,4] = -999

In [38]:
X

array([[   0.,    0.,    0.,    4.,    5.],
       [   0.,    0., -999.,    9.,   10.],
       [   0.,    0.,    0.,   14.,   15.],
       [  16.,   17.,   18.,   19.,   20.],
       [  21.,   22.,   23.,   24., -999.]])

### Printing Numpy Arrays

np automatically truncates the data when printing. Handy when you have _alot_ of data

In [39]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [40]:
# We can adjust these settings
np.set_printoptions(threshold=None)
print(np.arange(100).reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### Handling Multiple Data Types

In [41]:
T = np.array([['a','b','c'],[1,2,3],[.3,.55,1.2]])
T

array([['a', 'b', 'c'],
       ['1', '2', '3'],
       ['0.3', '0.55', '1.2']], dtype='<U4')

In [42]:
T = np.array([[1,2,3],[.3,.55,1.2]])
T

array([[1.  , 2.  , 3.  ],
       [0.3 , 0.55, 1.2 ]])

We'll rely on Pandas Data Frames when using use multiple data types.

### Some Useful Methods

In [43]:
X = np.random.randn(25).reshape(5,5)
X = X.round(2)
X

array([[ 0.77,  0.14,  1.48,  1.79,  0.54],
       [-1.81, -0.91, -1.03, -0.35, -0.99],
       [-1.13, -1.96, -1.88, -0.78, -0.91],
       [ 1.2 , -0.38,  1.16,  1.48,  1.08],
       [ 0.25,  1.79, -1.39, -1.09, -0.26]])

In [44]:
# Diagonal of a matrix
np.diag(X)

array([ 0.77, -0.91, -1.88,  1.48, -0.26])

In [45]:
# Index Location of the maximum value
np.argmax(X)

3

In [46]:
# Index Location of the minmum value
np.argmin(X)

11

In [47]:
print(X.flatten()[np.argmax(X)])
print(X.flatten()[np.argmin(X)])

1.79
-1.96


In [48]:
# Scan where a condition holds
np.where(X > 0)

(array([0, 0, 0, 0, 0, 3, 3, 3, 3, 4, 4]),
 array([0, 1, 2, 3, 4, 0, 2, 3, 4, 0, 1]))

In [49]:
X[np.where(X > 0)]

array([0.77, 0.14, 1.48, 1.79, 0.54, 1.2 , 1.16, 1.48, 1.08, 0.25, 1.79])

In [50]:
X[np.where(X < 0)]

array([-1.81, -0.91, -1.03, -0.35, -0.99, -1.13, -1.96, -1.88, -0.78,
       -0.91, -0.38, -1.39, -1.09, -0.26])

In [51]:
# Count the number of non-zero entries
np.count_nonzero(np.array([1,0,8,0,1]))

3

In [52]:
# scan for missing values
X[1,2] = np.nan
X[3,3] = np.nan
X[4,1] = np.nan
np.isnan(X)

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False,  True, False, False, False]])

In [53]:
~np.isnan(X) # are not NAs

array([[ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True, False,  True,  True,  True]])

In [54]:
# Replace missing values with zero
X[np.where(np.isnan(X))] = 0
X

array([[ 0.77,  0.14,  1.48,  1.79,  0.54],
       [-1.81, -0.91,  0.  , -0.35, -0.99],
       [-1.13, -1.96, -1.88, -0.78, -0.91],
       [ 1.2 , -0.38,  1.16,  0.  ,  1.08],
       [ 0.25,  0.  , -1.39, -1.09, -0.26]])

This is only scratching the surface! Play around with the library yourself!